server:
  port: 8090

eureka:
  client:
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
              
spring:
  application:
    name: gateway-service
  docker:
    enabled: true
    file: compose.yaml
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
      discovery:
        locator:
          enabled: true
      routes:
      - id: uploader-service
        uri: lb://uploader-service
        predicates:
        - Path=/uploader/**
        filters:
        - RewritePath=/uploader/(?<path>.*), /$\{path}