server:
  port: 8761

spring:
  application:
    name: discovery-service
  docker:
    enabled: true
    file: compose.yaml
    
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/